version: '3.8'
services:
  frontend:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - 8000:80
    depends_on:
      - api
    networks:
      - front_network

  api:
    image: pshaura/todolist_project:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      - postgresql
      - migration
    volumes:
      - ./.env:/usr/src/app/.env
    ports:
      - 8080:8000
    env_file:
      - ./.env
    networks:
      - front_network
      - db_network

  postgresql:
    image: postgres:13-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    networks:
      - db_network
    ports:
      - "5432:5432"

  migration:
    image: pshaura/todolist_project:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    command: python manage.py migrate --noinput
    volumes:
      - ./.env:/usr/src/app/.env
    depends_on:
      - postgresql
    networks:
      - db_network

volumes:
  postgres_data:


networks:
  db_network:
  front_network: