version: '3.9'

services:

  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      - postgresql
      - api
    networks:
      - front_network

  api:
    build: .
    depends_on:
      - migrations
      - postgresql
    ports:
      - "8000:8000"
    volumes:
      - ./.docker_env:/code/.env
    networks:
      - front_network
      - db_network


  migrations:
    build: .
    depends_on:
      - postgresql
    volumes:
      - ./.docker_env:/code/.env
    networks:
      - db_network
    command: python manage.py migrate --noinput


  bot:
    build: .
    depends_on:
      - migrations
      - postgresql
    volumes:
      - ./.docker_env:/code/.env
    networks:
      - db_network
    command: python manage.py runbot

  postgresql:
    image: postgres:12.4-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "5432:5432"
    networks:
      - db_network

volumes:
  postgres_data:


networks:
  db_network:
  front_network: