version: '3.9'

services:

  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      - db
      - api
    networks:
      - todolist_front_network


  api:
    image: pshaura/todolist_project:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    depends_on:
      - migrations
      - db
    volumes:
      - ./.env:/code/.env
    networks:
      - todolist_front_network
      - todolist_db_network

  migrations:
    image: pshaura/todolist_project:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    depends_on:
      - db
    volumes:
      - ./.env:/code/.env
    networks:
      - todolist_db_network
    command: python manage.py migrate --noinput

  bot:
    image: pshaura/todolist_project:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    depends_on:
      - migrations
      - db
    volumes:
      - ./.env:/code/.env
    networks:
      - todolist_db_network
    restart: always
    command: python manage.py runbot

  postgresql:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    networks:
      - todolist_db_network


volumes:
  postgres_data:


networks:
  todolist_db_network:
  todolist_front_network: