version: '3.8'

services:

  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "8080:80"
    depends_on:
      - db
      - api
    networks:
      - todolist_front_network

  api:
    build: .
    depends_on:
      - migrations
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./.docker_env:/code/.env
    networks:
      - todolist_front_network
      - todolist_db_network


  migrations:
    build: .
    depends_on:
      - db
    volumes:
      - ./.docker_env:/code/.env
    networks:
      - todolist_db_network
    command: python manage.py migrate --noinput


  bot:
    build: .
    depends_on:
      - migrations
      - db
    volumes:
      - ./.docker_env:/code/.env
    networks:
      - todolist_db_network
    command: python manage.py runbot

  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_adata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "5432:5432"
    networks:
      - todolist_db_network

volumes:
  postgres_data:


networks:
  todolist_db_network:
  todolist_front_network: