default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
        log_file: logs/pre-commit.log

    -   id: end-of-file-fixer
        log_file: logs/pre-commit.log


    -   id: trailing-whitespace
        log_file: logs/pre-commit.log

    -  id: check-json
       log_file: logs/pre-commit.log

 - repo: https://github.com/PyCQA/isort
   rev: 5.10.1
   hooks:
     -id: isort
 - repo: https://github.com/csachs/pyproject-flake8
   rev: v0.0.1a4
   hooks:
     - id: pyproject-flake8
       name: flake8
       entry: pflake8
       language: python
       types: [ python ]
       require_serial: true