[tools.isort]
line_lenght = 120
multi_line_output = 2
known_first_party = ['todolist', 'core', 'goals']

[tool.flake8]
max_line_leght = 120
per-file-ignores = """
    */migrations/*: E501
    .venv
    .env
    .docker_env
    .ci-env
"""
#[tool.flake8]
#max-line-length = 88
#extend-ignore = ["E203"]
#max-complexity = 10
#exclude = "venv"