name: Build and deploy action
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone cod
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -f ./Dockerfile -t pshaura/todolist:$GITHUB_REF_NAME .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push pshaura/todolist:$GITHUB_REF_NAME